### ISSUE TITLE
试了下，做开放性问答。感觉overfit啊

### ISSUE THREAD

**Issue by luyifanlu** [THUDM/GLM-130B#1]
如题

**Comment by Xiao9905** [comment]
@luyifanlu Hi，

请问你的测试内容是什么？是在什么数据集上进行的测试呢？

**Comment by luyifanlu** [comment]
> @luyifanlu Hi，
> 
> 请问你的测试内容是什么？是在什么数据集上进行的测试呢？

就一个2+3 = ，给出的output一大堆列式

**Comment by Sengxian** [comment]
the answer to 2+3 is [MASK].

**Comment by Sengxian** [comment]
如果不加任何 MASK 标记，模型默认会将 [gMASK] 加入输入末尾做长文本生成，在这种情况下 GLM-130B 的行为类似于 GPT 这类生成模型，输出列式的结果不可避免的，您可以[对比一下 BLOOM 176B 模型的生成结果](https://huggingface.co/bigscience/bloom?text=2%2B3%3D)。在这个场景下我们更推荐使用 GLM 的短文本填空能力：

输入：the answer to 2+3 is [MASK].
输出：the answer to 2+3 is 5 .

更多细节可以参考 [README](https://github.com/THUDM/GLM-130B#1-objective-autoregressive-blanking-infilling) 或者 [GLM的原始论文](https://aclanthology.org/2022.acl-long.26)。

感谢您的反馈！

**Comment by Sengxian** [comment]
这是 OpenAI GPT-3 API 给出的结果，供参考
GPT-3 (Davinci): 2+3 = 1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
