### ISSUE TITLE
Is it possible/recommended to do open generation?

### ISSUE THREAD

**Issue by LorrinWWW** [THUDM/GLM-130B#10]
Thanks for sharing the great work!

I'm curious if it is appropriate to do open generation. E.g. put only \[gMASK\] at the beginning and then complete the text.

Thank you again!

**Comment by Sengxian** [comment]
Hello @LorrinWWW. GLM-130B can still generate fluent sentences in this scenario, you can generate different sentences by changing the seed. However, we are also not sure if it is appropriate, it maybe depends on what you want to do.

**Comment by LorrinWWW** [comment]
Thanks for your answer! Another question is do you have any suggestion on performing batch generation?

**Comment by Sengxian** [comment]
Currently we don't support batch generation, but I'm guessing it's not too hard to modify the autoregressive generation logic and its corresponding strategy in [SAT](https://github.com/THUDM/SwissArmyTransformer/blob/934e2710a20f763c9a2a2eb02769a32bc79fff4d/SwissArmyTransformer/generation/autoregressive_sampling.py#L51) to support batch generation with a fixed context length (or no context).

**Comment by LorrinWWW** [comment]
Thank you very much!
