### ISSUE TITLE
想问一下作者，量化成int4 int8 之后为什么模型大小没有变化，都是240g

### ISSUE THREAD

**Issue by GXKIM** [THUDM/GLM-130B#172]
执行的这一段代码，改的路径和target-tp 4，target-tp 8

python tools/convert_tp.py \
    --input-folder <SRC_CKPT_PATH>  \
    --output-folder <DST_CKPT_PATH> \
    --target-tp 4

**Comment by sukibean163** [comment]
> 执行的这一段代码，改的路径和target-tp 4，target-tp 8
> 
> python tools/convert_tp.py --input-folder <SRC_CKPT_PATH> --output-folder <DST_CKPT_PATH> --target-tp 4

我也是，
![image](https://github.com/THUDM/GLM-130B/assets/24907968/d7f669bc-d590-4e52-9a8c-dc7e7dec9bfb)

**Comment by GXKIM** [comment]
> > 执行的这一段代码，改的路径和target-tp 4，target-tp 8
> > python tools/convert_tp.py --input-folder <SRC_CKPT_PATH> --output-folder <DST_CKPT_PATH> --target-tp 4
> 
> 我也是， ![image](https://user-images.githubusercontent.com/24907968/244588686-d7f669bc-d590-4e52-9a8c-dc7e7dec9bfb.png)

哈哈哈我也，所以想不通

**Comment by GXKIM** [comment]
> > 执行的这一段代码，改的路径和target-tp 4，target-tp 8
> > python tools/convert_tp.py --input-folder <SRC_CKPT_PATH> --output-folder <DST_CKPT_PATH> --target-tp 4
> 
> 想问下，在进行转换的时候，你的机器有多少的内存 大于260GB吗

嗯是的

**Comment by sukibean163** [comment]
> > 执行的这一段代码，改的路径和target-tp 4，target-tp 8
> > python tools/convert_tp.py --input-folder <SRC_CKPT_PATH> --output-folder <DST_CKPT_PATH> --target-tp 4
> 
> 我也是， ![image](https://user-images.githubusercontent.com/24907968/244588686-d7f669bc-d590-4e52-9a8c-dc7e7dec9bfb.png)

我猜量化文档命令有点问题，需要--quantization-bit-width，也就是python tools/convert_tp.py --input-folder THUDM/chatglm-130b/glm-130b-sat --output-folder THUDM/chatglm-130b-int4-test --target-tp 4 --quantization-bit-width 4，这样模型就小了
![image](https://github.com/THUDM/GLM-130B/assets/24907968/687eb1d2-6b7e-4b41-9654-d493f33b5002)

**Comment by GXKIM** [comment]
> > > 执行的这一段代码，改的路径和target-tp 4，target-tp 8
> > > python tools/convert_tp.py --input-folder <SRC_CKPT_PATH> --output-folder <DST_CKPT_PATH> --target-tp 4
> > 
> > 
> > 我也是， ![image](https://user-images.githubusercontent.com/24907968/244588686-d7f669bc-d590-4e52-9a8c-dc7e7dec9bfb.png)
> 
> 我猜量化文档命令有点问题，需要--quantization-bit-width，也就是python tools/convert_tp.py --input-folder THUDM/chatglm-130b/glm-130b-sat --output-folder THUDM/chatglm-130b-int4-test --target-tp 4 --quantization-bit-width 4，这样模型就小了 ![image](https://user-images.githubusercontent.com/24907968/244633145-687eb1d2-6b7e-4b41-9654-d493f33b5002.png)

不过为什么没有一些配置文件呢？

**Comment by sukibean163** [comment]
> > 执行的这一段代码，改的路径和target-tp 4，target-tp 8
> > python tools/convert_tp.py --input-folder <SRC_CKPT_PATH> --output-folder <DST_CKPT_PATH> --target-tp 4
> 
> 想问下，在进行转换的时候，你的机器有多少的内存 大于260GB吗

我是120G就可以了，swap空间大点就ok

**Comment by rchanggogogo** [comment]
> 



> > > 执行的这一段代码，改的路径和target-tp 4，target-tp 8
> > > python tools/convert_tp.py --input-folder <SRC_CKPT_PATH> --output-folder <DST_CKPT_PATH> --target-tp 4
> > 
> > 
> > 想问下，在进行转换的时候，你的机器有多少的内存 大于260GB吗
> 
> 我是120G就可以了，swap空间大点就ok

好的，多谢，我试试

**Comment by GXKIM** [comment]
int8 120g int4 60g左右

**Comment by guotong1988** [comment]
你们是怎么下载的啊 https://github.com/THUDM/GLM-130B/issues/176

**Comment by GXKIM** [comment]
> 你们是怎么下载的啊 #176

aria2 直接下载即可

**Comment by guotong1988** [comment]
不能直接下载，需要在docs.google填写申请表格，审批后下载url会发到邮箱里

**Comment by GXKIM** [comment]
> 不能直接下载，需要在docs.google填写申请表格，审批后下载url会发到邮箱里

文件里面有链接啊，直接下载就行了啊

**Comment by guotong1988** [comment]
> 文件里面有链接啊，直接下载就行了啊

哪个文件

**Comment by GXKIM** [comment]
> > 文件里面有链接啊，直接下载就行了啊
> 
> 哪个文件

填表，之后不是给你一个txt文件吗，你就按照那个下载，命令都有
