### ISSUE TITLE
int4模型加载报错

### ISSUE THREAD

**Issue by wudajun7509** [THUDM/GLM-130B#185]
File "/home/ai/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GLM130B:
        size mismatch for transformer.layers.0.attention.query_key_value.weight: copying a param with shape torch.Size([4608                        , 6144]) from checkpoint, the shape in current model is torch.Size([4608, 12288]).
        size mismatch for transformer.layers.0.attention.dense.weight: copying a param with shape torch.Size([12288, 768]) f                        rom checkpoint, the shape in current model is torch.Size([12288, 1536]).
        size mismatch for transformer.layers.0.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([12288, 2048]                        ) from checkpoint, the shape in current model is torch.Size([12288, 4096]).
        size mismatch for transformer.layers.0.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([8192, 6144])                         from checkpoint, the shape in current model is torch.Size([8192, 12288]).
        size mismatch for transformer.layers.1.attention.query_key_value.weight: copying a param with shape torch.Size([4608                        , 6144]) from checkpoint, the shape in current model is torch.Size([4608, 12288]).
        size mismatch for transformer.layers.1.attention.dense.weight: copying a par
这是什么原因呢？

**Comment by rchanggogogo** [comment]
> File "/home/ai/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for GLM130B: size mismatch for transformer.layers.0.attention.query_key_value.weight: copying a param with shape torch.Size([4608 , 6144]) from checkpoint, the shape in current model is torch.Size([4608, 12288]). size mismatch for transformer.layers.0.attention.dense.weight: copying a param with shape torch.Size([12288, 768]) f rom checkpoint, the shape in current model is torch.Size([12288, 1536]). size mismatch for transformer.layers.0.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([12288, 2048] ) from checkpoint, the shape in current model is torch.Size([12288, 4096]). size mismatch for transformer.layers.0.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([8192, 6144]) from checkpoint, the shape in current model is torch.Size([8192, 12288]). size mismatch for transformer.layers.1.attention.query_key_value.weight: copying a param with shape torch.Size([4608 , 6144]) from checkpoint, the shape in current model is torch.Size([4608, 12288]). size mismatch for transformer.layers.1.attention.dense.weight: copying a par 这是什么原因呢？

添加 "--from-quantized-checkpoint " 在 generate.sh 脚本

**Comment by wudajun7509** [comment]
感谢兄台回复，是这样吗？
bash scripts/generate.sh --input-source interactive --from-quantized-checkpoint 
这样运行确实加载了更长时间，但是还是报错：
size mismatch for transformer.layers.43.attention.query_key_value.weight: copying a param with shape torch.Size([9216, 6144]) from checkpoint, the s               hape in current model is torch.Size([9216, 12288]).

感觉shape正好差了一倍，多多指点哈。

**Comment by wudajun7509** [comment]
是我配置问题，目前已经可以加载，谢谢兄台！
