### ISSUE TITLE
GLM-130B + Contrastive Search?

### ISSUE THREAD

**Issue by yxuansu** [THUDM/GLM-130B#2]
Hi,

This work looks really interesting! 

I am curious about the performance of GLM with the SOTA decoding method, i.e. contrastive search [1], in open-ended text generation. Could you provide some examples generated by GLM with contrastive search? 

You can find a tutorial on how to apply contrastive search here (https://github.com/yxuansu/SimCTG#441-chinese-language-model). 

Many thanks! :-)

[1] - Su et al., 2022. [A Contrastive Framework for Neural Text Generation](https://arxiv.org/abs/2202.06417)

**Comment by Xiao9905** [comment]
@yxuansu Hi,

Thanks for your interest in our work! Unfortunately, we have too many issues to deal with recently, and we encourage you to have a try on adapting your contrastive search to GLM-130B (you can make pull requests to the [SAT](https://github.com/THUDM/SwissArmyTransformer), which implements GLM-130B and corresponding decoding strategies)! 

As GLM-130B is an open language model, we really welcome any of your valuable contributions to it!
