### ISSUE TITLE
Inference with FasterTransformer with GLB-130B

### ISSUE THREAD

**Issue by hamza-alethea** [THUDM/GLM-130B#20]
Hi!
I am trying to configure the GLM-130B models with FasterTransformer and I need to convert glm ckpt files, so where i can get **model_optim_rng.pt** file?
And I'm facing this
`CMake Error at cmake/Modules/FindNCCL.cmake:153 (message):
  Found NCCL header version and library version do not match! (include:
  /home/ubuntu/anaconda3/envs/glm/include, library:
  /home/ubuntu/anaconda3/envs/glm/lib/libnccl.so) Please set NCCL_INCLUDE_DIR
  and NCCL_LIB_DIR manually.
Call Stack (most recent call first):
  CMakeLists.txt:41 (find_package)`
while i'm trying to make build using this command `cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..`

My basic task is to minimize the inference time I also configured THUDM/GLM-130B main branch and I set **MAX_OUTPUT_LENGTH=64** it takes about 55s to generate a response.
Machine Specs: (V100) 8 * 32GB
Thanks

**Comment by hamza-alethea** [comment]
Thank you!
Do you know any other method which helps me to reduce response time for GLM-130B?

**Comment by Sengxian** [comment]
We have just released the quantized version of GLM-130B. The V100 servers can efficiently run the GLM-130B in INT8 precision, see [Quantization of GLM-130B](https://github.com/THUDM/GLM-130B/blob/main/docs/quantization.md) for details.

**Comment by Sengxian** [comment]
> > We have just released the quantized version of GLM-130B. The V100 servers can efficiently run the GLM-130B in INT8 precision, see [Quantization of GLM-130B](https://github.com/THUDM/GLM-130B/blob/main/docs/quantization.md) for details.
> > Hello,the Quantization  method referred in the link can also apply to GLM-10B model?

We haven't tried it, but I think a smaller model might be easier to do quantization.

**Comment by jiangliqin** [comment]
> > > We have just released the quantized version of GLM-130B. The V100 servers can efficiently run the GLM-130B in INT8 precision, see [Quantization of GLM-130B](https://github.com/THUDM/GLM-130B/blob/main/docs/quantization.md) for details.
> > > Hello,the Quantization  method referred in the link can also apply to GLM-10B model?
> 
> We haven't tried it, but I think a smaller model might be easier to do quantization.

i juset convert to 4-way for the GLM-10B,but i run the generate_block.sh,but failed to load the model
<img width="1738" alt="image" src="https://user-images.githubusercontent.com/12250847/186845282-27fdcda6-8584-47b1-8093-48f9b985088d.png">

**Comment by jiangliqin** [comment]
> > > > We have just released the quantized version of GLM-130B. The V100 servers can efficiently run the GLM-130B in INT8 precision, see [Quantization of GLM-130B](https://github.com/THUDM/GLM-130B/blob/main/docs/quantization.md) for details.
> > > > Hello,the Quantization  method referred in the link can also apply to GLM-10B model?
> > 
> > 
> > We haven't tried it, but I think a smaller model might be easier to do quantization.
> 
> i juset convert to 4-way for the GLM-10B,but i run the generate_block.sh,but failed to load the model <img alt="image" width="1738" src="https://user-images.githubusercontent.com/12250847/186845282-27fdcda6-8584-47b1-8093-48f9b985088d.png">

i change the MPSIZE to4 in the script

**Comment by jiangliqin** [comment]
用FasterTransformer加速推理中指定某个pt,还是整个pt的文件夹？
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/12250847/186873965-efb64cd3-8fa5-4a9c-97d9-f93212c35ac2.png">

**Comment by Sengxian** [comment]
Hello @jiangliqin! This repo is only for GLM-130B model, we have not yet do quantization for GLM-10B.
