### ISSUE TITLE
Inference with 3090*16

### ISSUE THREAD

**Issue by AnShengqiang** [THUDM/GLM-130B#21]
Hi,

I want to deploy GLM-130B to two 3090 * 8 nodes for inference (3090*16).

I think the memory is enough, but I'm not familiar with distributed inference.

Maybe I need to do the following things:
1. model parallel and pipeline parallel
2. a distributed API server
3. ...

Could you provide me with some ideas or materials?

Thanks.

**Comment by Sengxian** [comment]
Hello @AnShengqiang! Currently our framework does not support inference using pipeline parallelism. One possible solution is to convert the current checkpoint to 16-way tensor parallelism. However, this can be very efficient for inference. For this, a quantized version of the GLM-130B that allows efficient INT8 inference on the RTX 3090 servers will be released in the next few days, so please be patient and keep an eye on our GitHub repo.

**Comment by Sengxian** [comment]
We have just released the quantized version of GLM-130B. A single server with 8 * RTX 3090 can efficiently run the GLM-130B in INT8 precision, see [Quantization of GLM-130B](https://github.com/THUDM/GLM-130B/blob/main/docs/quantization.md) for details.

**Comment by AnShengqiang** [comment]
> We have just released the quantized version of GLM-130B. A single server with 8 * RTX 3090 can efficiently run GLM-130B in INT8 precision, see [Quantization of GLM-130B](https://github.com/THUDM/GLM-130B/blob/main/docs/quantization.md) for details.

Thanks!

**Comment by EasyLuck** [comment]
I have 4*RTX 3090 , each has 24GB. Can I do GLM-130B inference?
