### ISSUE TITLE
Question about finetuning

### ISSUE THREAD

**Issue by portia1026** [THUDM/GLM-130B#23]
Is there any tutorial/code on the finetuning of this GLM-130B model?

**Comment by Xiao9905** [comment]
@portia1026 Hi, 

Sorry for the late replay. We are still working on releasing code with regards to parameter-efficient tuning and fine-tuning on GLM-130B. However, currently we suggest to not consider *fine-tuning* GLM-130B, as we discover you may require tens of DGX A100 machines to make it.

A potential better idea is to use parameter-efficient learning approaches like P-Tuning/P-Tuning v2, which can cut down computing demands to very few DGX A100 nodes. Currently, it is better to consider tuning-free in-context learning.
