### ISSUE TITLE
language model evaluation at idx = 0

### ISSUE THREAD

**Issue by lomizandtyd** [THUDM/GLM-130B#24]
hi, I'm still looking for computing perplexity with GLM.

Just look into the recent updates on evaluation/{dataset.py, tasks.py} about language model task.

The code inside `dataset.py:LanguageModelTaskDataset:297`  is

```python
        if idx == 0 or self.config.unidirectional:
            prompt, text = tokens[:1], tokens[1:]
        else:
            prompt_length = self.config.max_seq_length - 1 - self.config.generation_length
            prompt, text = tokens[:prompt_length], tokens[prompt_length:]

        # ..... skip ....
        return {
            "tokens": np.array(prompt + [mask_id, sop_id] + text[:-1], dtype=np.int64),
            "targets": np.array(prompt + [mask_id] + text, dtype=np.int64),
            "position_ids": np.arange(0, seq_length, dtype=np.int64),
            "attention_mask": attention_mask < 0.5,
            "loss_masks": np.array([0] * (len(prompt) + 1) + [1] * len(text), dtype=np.int64),
        }
```
at `idx==0`, you take the full text as `prompt` input and also the output `text`.
It would lead to absolutely lower PPL. Because model has a full view of what it needs to predict.
Why wouldn't set the `prompt` to empty list?

**Comment by Sengxian** [comment]
Hello @lomizandtyd, I think `prompt = tokens[:1]` only takes the first character of the text not the full text.

**Comment by lomizandtyd** [comment]
yeah, my fault

**Comment by lomizandtyd** [comment]
I still got the question: Why wouldn't set the prompt to empty list?

**Comment by Sengxian** [comment]
> I still got the question: Why wouldn't set the prompt to empty list?

This is a mistake of mine, the prompt should be an empty list, I will fix it.

**Comment by lomizandtyd** [comment]
Got.
