### ISSUE TITLE
请教关于训练日志中的一些问题

### ISSUE THREAD

**Issue by XiaoqingNLP** [THUDM/GLM-130B#25]
我有如下问题想请教：
1. LargeScale 是一个开源工具包吗？我在搜索引擎和github中没有找到直接信息
2. 在测速中，更大的全局batch size `会有更大的吞吐，为什么最终会选择4224呢？另外，`BSZ=176 * 24=4224`，24正好是dp数，那176 需要梯度累加吗？大模型训练上用梯度累加跟小模型上会有显著差异吗？
3. 如下面所引用的，咱们中英文的数据都是纯文本，由多任务数据换回原中英文数据？对整个数据进行重新shuffle吗？这样会不会导致模型训练到重复的数据？这个shuffle对大模型训练的稳定作用这么大吗？
> 分析可能是 distribution 变动仍然太过剧烈，先换纯文本 + reshuffle 尝试训练

4. `warmup-samples-after-loading` 这个是什么操作？是从平衡的多任务，逐渐转换为带权重分布的多任务吗？
5. 这里的loss 爆炸体现在loss 上是nan 吗？还是只是突然增加数量级？

**Comment by Sengxian** [comment]
您好 @XiaoqingNLP 
1. 是我们自己的开发仓库名字
2. 在流水线并行下，一次个 batch 会被划分为若干 micro batch 来减少流水线的气泡，因此梯度累加是必须使用的。具体来说，我们采用的是 1F1B 的流水线 schedule。
3. 这个只是我们排查不收敛是不是 reshuffle 导致的，此外这部分在日志中标记了（废除），最终的训练曲线没有这一段。
4. 是的，我们发现需要缓慢改变数据的分布，否则会导致训练不收敛。
5. 一般观察到的现象是 loss 先 spike 到几个数量级以上，再 nan。

**Comment by eyuansu62** [comment]
请问LargeScale有开源版本吗？
