### ISSUE TITLE
How to cite the repo

### ISSUE THREAD

**Issue by younesbelkada** [THUDM/GLM-130B#26]
Hi there!

Thanks for the great work!
Was wondering how can we cite this work ?

Thanks

**Comment by Xiao9905** [comment]
@younesbelkada Hi,

Thanks for your interest! Is it urgent for you add the citation? Our paper is in its final proofreading period, and will be released next week. At that time you can cite our paper : )

If you are immediately about to release some paper or technical report, you can cite this one (only temporarily):

@article{zeng2022GLM,
  title={GLM-130B: An Open Bilingual Pre-Trained Model},
  author={Zeng, Aohan and Liu, Xiao and Du, Zhengxiao and Ding, Ming and Zheng, Qinkai and Lai, Hanyu and Wang, Zihan and Yang, Zhuoyi and Yu, Jifan and Zhang, Xiaohan and Zheng, Wendi and Xia, Xiao and Xu, Yifan and Tam, Weng Lam and Dong, Yuxiao and Ma, Zixuan and He, Jiaao and Sun, Zhenbo and Zhai, Jidong and Chen, Wengguang and Zeng, Guoyang and Han, Xu and Zhao, Weilin and Liu, Zhiyuan and Xue, Yufei and Wang, Shan and Shan, Jiecai and Jiang, Haohan and Guo, Zhengang and Zhang, Peng and Tang, Jie},
  year={2022},
  publisher={Technical report, Tsinghua KEG},
  url={https://keg.cs.tsinghua.edu.cn/glm-130b/}
}

**Comment by younesbelkada** [comment]
Thanks a lot for the quick answer 🔥 !
It is not urgent at all, I just wanted to properly cite your work and repo on a technical report, the citation mentioned above should be sufficient ;) 
Thanks again!

**Comment by Xiao9905** [comment]
@younesbelkada ,

Thanks! We will inform you once our paper be out next week!

**Comment by Xiao9905** [comment]
@XiaoqingNLP @younesbelkada ,

Thanks for your patient waiting! Our paper is now [out](https://arxiv.org/abs/2210.02414). You may read it and cite in your later work via:

```
@article{zeng2022glm130b,
  title={GLM-130B: An Open Bilingual Pre-trained Model},
  author={Aohan Zeng and Xiao Liu and Zhengxiao Du and Zihan Wang and Hanyu Lai and Ming Ding and Zhuoyi Yang and Yifan Xu and Wendi Zheng and Xiao Xia and Weng Lam Tam and Zixuan Ma and Yufei Xue and Jidong Zhai and Wenguang Chen and P. Zhang and Yuxiao Dong and Jie Tang},
  journal={arXiv:2210.02414},
  year={2022}
}
```
