### ISSUE TITLE
What is the device requirement for only-generatation (zero-shot)

### ISSUE THREAD

**Issue by debby1103** [THUDM/GLM-130B#27]
What is the device requirement for only generatation (zero-shot)

**Comment by Sengxian** [comment]
4 * RTX 3090 or 8 * RTX 2080 Ti (or 1080 Ti) is the minimal requirement for generating 2048 length sequences. Check [here](https://github.com/THUDM/GLM-130B/blob/main/docs/quantization.md#space-and-speed-benchmark) for details.
