### ISSUE TITLE
Tensor parallel dimension conversion script fails

### ISSUE THREAD

**Issue by dylan-slack** [THUDM/GLM-130B#29]
Hello!

It seems the script for converting the tensor parallel dimension fails

Running for instance

```bash
python tools/convert_tp.py --input-folder "../glm/glm-130b-sat" --output-folder "../glm/four-div-glm-130b-sat" --target-tp 4
```

Yields

```
Traceback (most recent call last):
  File "/extra/ucinlp1/dylan/GLM-130B/tools/convert_tp.py", line 154, in <module>
    main(args)
  File "/extra/ucinlp1/dylan/GLM-130B/tools/convert_tp.py", line 149, in main
    torch.save(create_checkpoint(sd_list, i, original_tp, args.target_tp, args.quantization_bit_width), save_path)
  File "/extra/ucinlp1/dylan/GLM-130B/tools/convert_tp.py", line 121, in create_checkpoint
    new_sd[key], new_sd[f"{key}_scale"] = new_sd[key]
ValueError: too many values to unpack (expected 2)
```

Any advice here? Thanks 🙏🏻

**Comment by dylan-slack** [comment]
Oh, it seems setting the quantization bit width leads to success, e.g.,

```
python tools/convert_tp.py --input-folder "../glm/glm-130b-sat" --output-folder "../glm/four-div-glm-130b-sat" --target-tp 4 --quantization-bit-width 8
```

works.

Worth noting that it seems like the script crashes if you try and run without quantization.

**Comment by Sengxian** [comment]
Sorry, this issue is fixed in the [latest commit](https://github.com/THUDM/GLM-130B/commit/f9276c6988749d547e947ae915a178129c143255).

**Comment by todiketan** [comment]
<img width="1071" alt="Screenshot 2022-10-15 at 7 05 51 AM" src="https://user-images.githubusercontent.com/18617396/195983138-83da863b-ae98-4682-bddd-a7d8ab5c5307.png">

I tried running the script with the quantization_width set, but am getting the error as cpm_kernels not found, can anyone help me with it.
Thanks!
