### ISSUE TITLE
Clarification on reported dataset size for the Pile (`1.2T` vs `825GiB`)

### ISSUE THREAD

**Issue by tholiao** [THUDM/GLM-130B#3]
Hi, thanks for releasing code and weights for GLM-130B.

The README says that GLM-130B was trained partly on `1.2T Pile corpus for English`. The Pile size is `825 GiB` or `0.886 TB`. 

Was there any English data used to train GLM-130B in addition to the Pile?

**Comment by Xiao9905** [comment]
@tholiao Hi,

Thanks for your interest in our work! We use the official [weighted Pile corpus (Table 1, as shown below)](https://arxiv.org/pdf/2101.00027.pdf), which duplicates several dataset and thus increases the raw size from Raw Size 825.18GB to Effective Size 1254.20 GB. We report the actual size of the corpus on our disk (which is the "Effective Size" in the table), so it is 1.2TB.

Thanks for your pointing out, and we will clarify the detail in our technical report (coming soon!).

<img width="633" alt="image" src="https://user-images.githubusercontent.com/35831349/183276066-106ba585-9dc5-468d-a31a-4850a1aad8cc.png">
