### ISSUE TITLE
INT8 inference 

### ISSUE THREAD

**Issue by david-macleod** [THUDM/GLM-130B#35]
Hi, in your paper you talk about using INT8 dtype to store the weights, but they are cast to FP16 for the calculation. I was just wondering if at inference time do you actually calculate in INT8 (rather than FP16) given that you are using fastertransformer and that has support kernels which use INT8 tensor cores, to obtain an improvement in speed

**Comment by Sengxian** [comment]
Hi @david-macleod. Currently we cannot use INT8 GEMM because the activation outliers make the quantization difficult. We are still working on quantizing the activation to INT8.
