### ISSUE TITLE
M1Max 64G inference support? or even M2Max (in future)?

### ISSUE THREAD

**Issue by lockmatrix** [THUDM/GLM-130B#4]
I think it is cheaper.

**Comment by Xiao9905** [comment]
@lockmatrix Hi,

Interesting point. I think it worths a trial, but the problem may lie in the intolerable speed (as the memory cannot contain the full checkpoint of 260G, we need frequent disk swapping and it can be even slower compared to swapping between main memory and GPU memory).

What's your view on the speed of GLM-130B's inference? When resources are limited, do you prefer to sacrifice more generation performance or speed?

**Comment by lockmatrix** [comment]
er, 260G is too much, it needs a smaller model for pc

**Comment by lockmatrix** [comment]
> What's your view on the speed of GLM-130B's inference? When resources are limited, do you prefer to sacrifice more generation performance or speed?

I prefer sacrifice more generation performance, It will be much more useful if a cheaper PC can inference it.

**Comment by Xiao9905** [comment]
@lockmatrix ,

Have you ever tried [GLM's 10 billion version](https://github.com/THUDM/GLM)? We provide an English and a Chinese monolingual GLM-10B version, and according to my estimation, it only requires about 40G memory when using FP16.

**Comment by lockmatrix** [comment]
> Have you ever tried [GLM's 10 billion version](https://github.com/THUDM/GLM)? We provide an English and a Chinese monolingual GLM-10B version, and according to my estimation, it only requires about 40G memory when using FP16.

No.
I will try it when I get a M1Max

**Comment by Xiao9905** [comment]
Great. Thanks for your advice.
