### ISSUE TITLE
一直无法添加微信群？

### ISSUE THREAD

**Issue by Dinxin** [THUDM/GLM-130B#44]
我发送了好多次添加请求，都没有得到回应，都是已过期。

**Comment by Xiao9905** [comment]
@Dinxin 你好，

能具体描述一下问题么？是无法添加小呆好友，还是无法通过加小呆好友后的加入群聊邀请入群？

**Comment by Xiao9905** [comment]
请问您可以入群了么？我们测试了一下入群流程，可能是添加小呆的用户过多，导致小呆有时无法直接回应。如果您继续遇到无法添加小呆的问题，请稍等再添加即可。
