### ISSUE TITLE
Is bilingual GLM with smaller model size like 1.5B, 2.7B available? 

### ISSUE THREAD

**Issue by BrightXiaoHan** [THUDM/GLM-130B#45]
Hi!
I have checked #9. But there are all monolingual models. Is bilingual GLM with smaller model sizes like 1.5B, 2.7B available?

**Comment by Xiao9905** [comment]
@BrightXiaoHan There is a [multilingual (104 languages) 1B GLM](https://github.com/THUDM/Multilingual-GLM) model listed in our README. We haven't trained or planned to release other bilingual GLMs yet.
