### ISSUE TITLE
The config for glm-10b

### ISSUE THREAD

**Issue by xxupiano** [THUDM/GLM-130B#47]
I need to use the glm-10b with scripts/generate.sh and set MODEL_TYPE='glm-10b' in the config file in *configs*.

However, there are still errors that [Errno 2] No such file or directory: 'XXX/glm-10b-en/126000/mp_rank_01_model_states.pt' and [Errno 2] No such file or directory: 'XXX/glm-10b-en/126000/mp_rank_02_model_states.pt' maybe because glm_130b is used.

How can be the config file modified in *configs* to use glm-10b instead of glm-130b?

Looking forward to reply. Thanks.

**Comment by xxupiano** [comment]
According to the log, maybe *tokenizer-type* need to be modified. What is the glm-10b-en tokenizer type?

**Comment by Xiao9905** [comment]
@xxupiano Hi,

Which repository of code are you using? The code in this repo (GLM-130B) is for the 130B version only. If you want to use monolingual GLM-10B, please use the framework in [GLM's original repo](https://github.com/THUDM/GLM).

**Comment by xxupiano** [comment]
Thanks for your reply. I'll try that repo.
