### ISSUE TITLE
4x 80gb A100 vs 8x 40gb A100

### ISSUE THREAD

**Issue by smeyerhot** [THUDM/GLM-130B#50]
GCP prices 8x 40gb A100's at 50% more than 4x 80gb A100's. Would I be able to accomplish the same results with a little tweaking of the default config?

**Comment by smeyerhot** [comment]
When I tried to load the model earlier it looked like the weights were divided into 8 "pieces". Wondering if there is a simple way to split them 4 ways with each being "twice as big".

**Comment by Sengxian** [comment]
See https://github.com/THUDM/GLM-130B#model-weights for checkpoint conversion script.
