### ISSUE TITLE
how to batch inference

### ISSUE THREAD

**Issue by jimmycrowoo** [THUDM/GLM-130B#51]
How to  batch inference? Thanks!

**Comment by Sengxian** [comment]
Currently, our [FasterTransformer](https://github.com/THUDM/GLM-130B/blob/main/docs/inference-with-fastertransformer.md) backend have a batch inference API. Or you can leverage `GenerationTaskDataset` to implement batch inference as shown [here](https://github.com/THUDM/GLM-130B/blob/b31b6a9c1496088cede69ec19db777fab037e901/evaluation/bigbench.py#L22).
