### ISSUE TITLE
How to use the code for multinode inference?

### ISSUE THREAD

**Issue by tomyoung903** [THUDM/GLM-130B#53]
Hi really appreciate the great work!

I am wondering, is there a straightforward way to adapt the code for multinode inference?

I got 3 A100s each with 3 GPUs of 40GB memory.

Does this code naturally support multinode inference? If so where in the code shall I tune it?

Thanks!

**Comment by Sengxian** [comment]
See https://github.com/THUDM/GLM-130B#model-weights for checkpoint conversion script. You may use INT4 quantization for 3*40G A100s.

**Comment by tomyoung903** [comment]
Hi thanks for the response. But I guess I didn't make myself clear. 

I have enough gpus so no quantization is needed for me.

However, those gpus exist among multiple nodes (machines) managed under a single slurm manager.

So what I need is multi-node inference. The model weights need to exist among the gpus in multiple nodes.

The code in this repo assumes single node: no_procs_per_node = mp_size

Do you have advice on adapting the code to multinode inference?

**Comment by Sengxian** [comment]
You can adapt [this multi-node evaluation script](https://github.com/THUDM/GLM-130B/blob/main/scripts/evaluate_multiple_node.sh) to a multi-node generation. With arguments like `NUM_WORKERS=8` and `NUM_GPUS_PER_WORKER=1`.

**Comment by tomyoung903** [comment]
much thanks. but I did it with just torchrun with some rdzv arguments
