### ISSUE TITLE
is code generation pretraining task 

### ISSUE THREAD

**Issue by zhouliang-yu** [THUDM/GLM-130B#54]
Hey, thx for releasing this amazing work!
I wonder do you pre-train this model on code generation tasks?

**Comment by Sengxian** [comment]
At present, our code corpus is only from the Github subset of The Pile dataset. You can check [our paper](http://arxiv.org/abs/2210.02414) for the details of pre-training datasets.

**Comment by zhouliang-yu** [comment]
thx
