### ISSUE TITLE
BIG-bench-lite evaluation code

### ISSUE THREAD

**Issue by tomyoung903** [THUDM/GLM-130B#57]
Hi thanks for the great work!

Is there a plan on sharing the code and data you specifically used for evaluating BIG-bench-lite?

It might be important for recreating the results given the decision points regarding prompt design etc.

**Comment by Sengxian** [comment]
Our current Big-Bench benchmark code is published in the [dev branch](https://github.com/THUDM/GLM-130B/blob/dev/scripts/evaluate_bigbench.sh). The results reported in the paper completely use official prompts without modification. However, we found that the few-shot performance of GLM-130B is very strange under those official prompts, which is much weaker than our own construction few-shot prompts, we are still working on this.
