### ISSUE TITLE
generate.py could not deal with multi lines input？

### ISSUE THREAD

**Issue by cyente** [THUDM/GLM-130B#61]
It seems that the tokenizer ’‘icetk-glm-130B’‘ of swisstransformer is import from icetk

 the encoder in  icetk[https://github.com/THUDM/icetk/blob/ffd8def44769ff58b6aed97ea831749487e4316e/icetk/ice_tokenizer.py#L62：](https://github.com/THUDM/icetk/blob/ffd8def44769ff58b6aed97ea831749487e4316e/icetk/ice_tokenizer.py#L62%EF%BC%9A) is has the default setting：ignore_linebreak=True

However, in  SwissAmryTransformer ignore_linebreak is not given.
https://github.com/THUDM/SwissArmyTransformer/blob/ddfcea5215ac98742805ce07f7874b2495275e61/SwissArmyTransformer/tokenization/icetk_glm_130B/ice_tokenizer.py#L83

**Comment by Sengxian** [comment]
Hello @cyente, you can use `<n>` as a replace of `\n` in prompt.

**Comment by cyente** [comment]
Thanks～that helps me a lot
