### ISSUE TITLE
量化后，模型载入报错

### ISSUE THREAD

**Issue by jimmycrowoo** [THUDM/GLM-130B#62]
我在v100机器上，使用int8量化，按照教程在model_glm_130b_int8.sh中配置了模型路径，然后在script/generate.sh 改为了source "${main_dir}/configs/model_glm_130b_int8.sh" 
使用以下脚本运行 bash scripts/generate.sh --input-source input.txt --from-quantized-checkpoint
有如下报错：raise ValueError(f'Missing keys for inference: {missing_keys}.')
ValueError: Missing keys for inference: ['transformer.layers.0.attention.query_key_value.weight_scale', 'transformer.layers.0.attention.dense.weight_scale', 'transformer.layers.0.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.0.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.1.attention.query_key_value.weight_scale', 'transformer.layers.1.attention.dense.weight_scale', 'transformer.layers.1.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.1.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.2.attention.query_key_value.weight_scale', 'transformer.layers.2.attention.dense.weight_scale', 'transformer.layers.2.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.2.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.3.attention.query_key_value.weight_scale', 'transformer.layers.3.attention.dense.weight_scale', 'transformer.layers.3.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.3.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.4.attention.query_key_value.weight_scale', 'transformer.layers.4.attention.dense.weight_scale', 'transformer.layers.4.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.4.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.5.attention.query_key_value.weight_scale', 'transformer.layers.5.attention.dense.weight_scale', 'transformer.layers.5.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.5.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.6.attention.query_key_value.weight_scale', 'transformer.layers.6.attention.dense.weight_scale', 'transformer.layers.6.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.6.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.7.attention.query_key_value.weight_scale', 'transformer.layers.7.attention.dense.weight_scale', 'transformer.layers.7.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.7.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.8.attention.query_key_value.weight_scale', 'transformer.layers.8.attention.dense.weight_scale', 'transformer.layers.8.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.8.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.9.attention.query_key_value.weight_scale', 'transformer.layers.9.attention.dense.weight_scale', 'transformer.layers.9.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.9.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.10.attention.query_key_value.weight_scale', 'transformer.layers.10.attention.dense.weight_scale', 'transformer.layers.10.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.10.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.11.attention.query_key_value.weight_scale', 'transformer.layers.11.attention.dense.weight_scale', 'transformer.layers.11.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.11.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.12.attention.query_key_value.weight_scale', 'transformer.layers.12.attention.dense.weight_scale', 'transformer.layers.12.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.12.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.13.attention.query_key_value.weight_scale', 'transformer.layers.13.attention.dense.weight_scale', 'transformer.layers.13.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.13.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.14.attention.query_key_value.weight_scale', 'transformer.layers.14.attention.dense.weight_scale', 'transformer.layers.14.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.14.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.15.attention.query_key_value.weight_scale', 'transformer.layers.15.attention.dense.weight_scale', 'transformer.layers.15.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.15.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.16.attention.query_key_value.weight_scale', 'transformer.layers.16.attention.dense.weight_scale', 'transformer.layers.16.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.16.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.17.attention.query_key_value.weight_scale', 'transformer.layers.17.attention.dense.weight_scale', 'transformer.layers.17.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.17.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.18.attention.query_key_value.weight_scale', 'transformer.layers.18.attention.dense.weight_scale', 'transformer.layers.18.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.18.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.19.attention.query_key_value.weight_scale', 'transformer.layers.19.attention.dense.weight_scale', 'transformer.layers.19.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.19.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.20.attention.query_key_value.weight_scale', 'transformer.layers.20.attention.dense.weight_scale', 'transformer.layers.20.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.20.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.21.attention.query_key_value.weight_scale', 'transformer.layers.21.attention.dense.weight_scale', 'transformer.layers.21.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.21.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.22.attention.query_key_value.weight_scale', 'transformer.layers.22.attention.dense.weight_scale', 'transformer.layers.22.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.22.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.23.attention.query_key_value.weight_scale', 'transformer.layers.23.attention.dense.weight_scale', 'transformer.layers.23.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.23.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.24.attention.query_key_value.weight_scale', 'transformer.layers.24.attention.dense.weight_scale', 'transformer.layers.24.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.24.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.25.attention.query_key_value.weight_scale', 'transformer.layers.25.attention.dense.weight_scale', 'transformer.layers.25.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.25.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.26.attention.query_key_value.weight_scale', 'transformer.layers.26.attention.dense.weight_scale', 'transformer.layers.26.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.26.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.27.attention.query_key_value.weight_scale', 'transformer.layers.27.attention.dense.weight_scale', 'transformer.layers.27.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.27.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.28.attention.query_key_value.weight_scale', 'transformer.layers.28.attention.dense.weight_scale', 'transformer.layers.28.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.28.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.29.attention.query_key_value.weight_scale', 'transformer.layers.29.attention.dense.weight_scale', 'transformer.layers.29.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.29.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.30.attention.query_key_value.weight_scale', 'transformer.layers.30.attention.dense.weight_scale', 'transformer.layers.30.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.30.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.31.attention.query_key_value.weight_scale', 'transformer.layers.31.attention.dense.weight_scale', 'transformer.layers.31.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.31.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.32.attention.query_key_value.weight_scale', 'transformer.layers.32.attention.dense.weight_scale', 'transformer.layers.32.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.32.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.33.attention.query_key_value.weight_scale', 'transformer.layers.33.attention.dense.weight_scale', 'transformer.layers.33.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.33.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.34.attention.query_key_value.weight_scale', 'transformer.layers.34.attention.dense.weight_scale', 'transformer.layers.34.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.34.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.35.attention.query_key_value.weight_scale', 'transformer.layers.35.attention.dense.weight_scale', 'transformer.layers.35.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.35.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.36.attention.query_key_value.weight_scale', 'transformer.layers.36.attention.dense.weight_scale', 'transformer.layers.36.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.36.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.37.attention.query_key_value.weight_scale', 'transformer.layers.37.attention.dense.weight_scale', 'transformer.layers.37.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.37.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.38.attention.query_key_value.weight_scale', 'transformer.layers.38.attention.dense.weight_scale', 'transformer.layers.38.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.38.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.39.attention.query_key_value.weight_scale', 'transformer.layers.39.attention.dense.weight_scale', 'transformer.layers.39.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.39.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.40.attention.query_key_value.weight_scale', 'transformer.layers.40.attention.dense.weight_scale', 'transformer.layers.40.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.40.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.41.attention.query_key_value.weight_scale', 'transformer.layers.41.attention.dense.weight_scale', 'transformer.layers.41.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.41.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.42.attention.query_key_value.weight_scale', 'transformer.layers.42.attention.dense.weight_scale', 'transformer.layers.42.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.42.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.43.attention.query_key_value.weight_scale', 'transformer.layers.43.attention.dense.weight_scale', 'transformer.layers.43.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.43.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.44.attention.query_key_value.weight_scale', 'transformer.layers.44.attention.dense.weight_scale', 'transformer.layers.44.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.44.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.45.attention.query_key_value.weight_scale', 'transformer.layers.45.attention.dense.weight_scale', 'transformer.layers.45.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.45.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.46.attention.query_key_value.weight_scale', 'transformer.layers.46.attention.dense.weight_scale', 'transformer.layers.46.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.46.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.47.attention.query_key_value.weight_scale', 'transformer.layers.47.attention.dense.weight_scale', 'transformer.layers.47.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.47.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.48.attention.query_key_value.weight_scale', 'transformer.layers.48.attention.dense.weight_scale', 'transformer.layers.48.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.48.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.49.attention.query_key_value.weight_scale', 'transformer.layers.49.attention.dense.weight_scale', 'transformer.layers.49.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.49.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.50.attention.query_key_value.weight_scale', 'transformer.layers.50.attention.dense.weight_scale', 'transformer.layers.50.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.50.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.51.attention.query_key_value.weight_scale', 'transformer.layers.51.attention.dense.weight_scale', 'transformer.layers.51.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.51.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.52.attention.query_key_value.weight_scale', 'transformer.layers.52.attention.dense.weight_scale', 'transformer.layers.52.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.52.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.53.attention.query_key_value.weight_scale', 'transformer.layers.53.attention.dense.weight_scale', 'transformer.layers.53.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.53.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.54.attention.query_key_value.weight_scale', 'transformer.layers.54.attention.dense.weight_scale', 'transformer.layers.54.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.54.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.55.attention.query_key_value.weight_scale', 'transformer.layers.55.attention.dense.weight_scale', 'transformer.layers.55.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.55.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.56.attention.query_key_value.weight_scale', 'transformer.layers.56.attention.dense.weight_scale', 'transformer.layers.56.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.56.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.57.attention.query_key_value.weight_scale', 'transformer.layers.57.attention.dense.weight_scale', 'transformer.layers.57.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.57.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.58.attention.query_key_value.weight_scale', 'transformer.layers.58.attention.dense.weight_scale', 'transformer.layers.58.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.58.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.59.attention.query_key_value.weight_scale', 'transformer.layers.59.attention.dense.weight_scale', 'transformer.layers.59.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.59.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.60.attention.query_key_value.weight_scale', 'transformer.layers.60.attention.dense.weight_scale', 'transformer.layers.60.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.60.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.61.attention.query_key_value.weight_scale', 'transformer.layers.61.attention.dense.weight_scale', 'transformer.layers.61.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.61.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.62.attention.query_key_value.weight_scale', 'transformer.layers.62.attention.dense.weight_scale', 'transformer.layers.62.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.62.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.63.attention.query_key_value.weight_scale', 'transformer.layers.63.attention.dense.weight_scale', 'transformer.layers.63.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.63.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.64.attention.query_key_value.weight_scale', 'transformer.layers.64.attention.dense.weight_scale', 'transformer.layers.64.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.64.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.65.attention.query_key_value.weight_scale', 'transformer.layers.65.attention.dense.weight_scale', 'transformer.layers.65.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.65.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.66.attention.query_key_value.weight_scale', 'transformer.layers.66.attention.dense.weight_scale', 'transformer.layers.66.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.66.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.67.attention.query_key_value.weight_scale', 'transformer.layers.67.attention.dense.weight_scale', 'transformer.layers.67.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.67.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.68.attention.query_key_value.weight_scale', 'transformer.layers.68.attention.dense.weight_scale', 'transformer.layers.68.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.68.mlp.dense_h_to_4h.weight_scale', 'transformer.layers.69.attention.query_key_value.weight_scale', 'transformer.layers.69.attention.dense.weight_scale', 'transformer.layers.69.mlp.dense_4h_to_h.weight_scale', 'transformer.layers.69.mlp.dense_h_to_4h.weight_scale'].

**Comment by Sengxian** [comment]
不用加 ` --from-quantized-checkpoint`，因为你是动态量化的。
