### ISSUE TITLE
np bool issue

### ISSUE THREAD

**Issue by HillZhang1999** [THUDM/GLM-130B#72]
When I used GLM-130B for generation, I met this error:
```
  File "/root/data/nas_alinlp/yueding/GLM-130B/generation/strategies.py", line 80, in _init_cache
        self._is_done = np.zeros(self.batch_size, dtype=np.bool)
  AttributeError: module 'numpy' has no attribute 'bool'
```
I fixed this error by specifying the version of numpy to 1.23.1 since `np.bool` support was dropped on numpy 1.24.0
https://github.com/numpy/numpy/pull/22607.

**Comment by Sengxian** [comment]
Hello @HillZhang1999, for numpy >= 1.24, you may use `np.bool_` instead of `np.bool`. Thanks for pointing this out!

**Comment by HillZhang1999** [comment]
Thanks a lot
