### ISSUE TITLE
模型微调

### ISSUE THREAD

**Issue by Xuekai-Zhu** [THUDM/GLM-130B#73]
请问我能够直接在3090上微调 你们的10B模型吗？

**Comment by Xiao9905** [comment]
@Xuekai-Zhu 你好，

10B的微调，请参考[https://github.com/THUDM/GLM](https://github.com/THUDM/GLM)仓库。3090 (24G)版本在使用fp16，并加上zero-3优化，以及很小的batch size时是有可能在3090 (24G)上进行微调的。
