### ISSUE TITLE
Triton FasterTransformer Backend

### ISSUE THREAD

**Issue by eugenesiow** [THUDM/GLM-130B#8]
Great work!
Any plans to integrate the FasterTransformer recipe and code (https://github.com/THUDM/GLM-130B/blob/main/docs/inference-with-fastertransformer.md) with the Triton FasterTransformer backend (https://github.com/triton-inference-server/fastertransformer_backend)?

**Comment by Sengxian** [comment]
Thank you for your attention! Unfortunately, we are currently busy preparing our paper and have no plan to support the Triton backend. We welcome PRs from the community to make the model more accessible since GLM-130B is an open source language model.
