### ISSUE TITLE
8*A100加载GLM-130B模型报错

### ISSUE THREAD

**Issue by iMountTai** [THUDM/GLM-130B#81]
**Versions**
```
PyTorch version: 1.12.1
CUDA used to build PyTorch: 11.3
Python:3.9
DeepSpeed 0.8
Apex
SwissArmyTransformer==0.2.12
```
![image](https://user-images.githubusercontent.com/35353688/217705417-20d8c8e6-dd58-438c-a3fa-9ab809c86669.png)
但是加载int8或者int4是没有问题的，不知有没有该问题的解决方案，谢谢！

**Comment by iMountTai** [comment]
已解决，是内存不够的原因。

**Comment by Iteravse** [comment]
> 已解决，是内存不够的原因。

请问多少内存够用
