### ISSUE TITLE
Is GLM with smaller model size like 1.5B, 2.7B available?

### ISSUE THREAD

**Issue by LeeSureman** [THUDM/GLM-130B#9]

**Comment by Sengxian** [comment]
Thanks for your attention! Please checkout [this repo](https://github.com/THUDM/GLM) for GLM at 110M to 10B scale. [SAT](https://github.com/THUDM/SwissArmyTransformer) also provides a convenient way to download and use the 10B GLM.

**Comment by LeeSureman** [comment]
very appreciated for your quick response!
